# Entryptor CI/CD Pipeline
# Test Python application on multiple platforms and build macOS app

trigger:
- main

pr:
- main

variables:
  pythonVersion: '3.11'

stages:
- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestMultiplePython
    displayName: 'Test on Multiple Python Versions (Linux)'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
        Python310:
          python.version: '3.10'
        Python311:
          python.version: '3.11'
        Python312:
          python.version: '3.12'
    steps:
    - template: pipelines/templates/test-steps.yml
      parameters:
        pythonVersion: '$(python.version)'

  - job: TestCrossPlatform
    displayName: 'Test Cross-Platform'
    strategy:
      matrix:
        Linux:
          imageName: 'ubuntu-latest'
          displayName: 'Linux'
        macOS:
          imageName: 'macOS-latest'
          displayName: 'macOS'
        Windows:
          imageName: 'windows-latest'
          displayName: 'Windows'
    pool:
      vmImage: $(imageName)
    steps:
    - template: pipelines/templates/test-steps.yml
      parameters:
        pythonVersion: $(pythonVersion)
        platform: $(displayName)

- stage: Build
  displayName: 'Build Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: BuildMacOS
    displayName: 'Build macOS Application'
    pool:
      vmImage: 'macOS-latest'
    steps:
    - template: pipelines/templates/build-steps.yml
      parameters:
        pythonVersion: $(pythonVersion)
        platform: 'macOS'
        artifactName: 'entryptor-macos'
