# Entryptor Minimal CI/CD Pipeline
# Single job pipeline to work with free Azure DevOps parallelism

trigger:
- main

pr:
- main

variables:
  pythonVersion: '3.11'

jobs:
- job: TestAndBuild
  displayName: 'Test and Build Entryptor'
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  # Test Steps
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    displayName: 'Install dependencies'

  - script: |
      python -m ruff check src/ tests/
    displayName: 'Run Ruff Linting'

  - script: |
      python -m mypy src/
    displayName: 'Run MyPy Type Checking'

  - script: |
      python -m pytest tests/ -v --tb=short --junitxml=test-results.xml --cov=src --cov-report=xml
    displayName: 'Run Tests with Coverage'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Python $(pythonVersion) Tests'
      failTaskOnFailedTests: true
    displayName: 'Publish Test Results'

  # Build Steps
  - script: |
      pip install pyinstaller
    displayName: 'Install PyInstaller'

  - script: |
      pyinstaller --onefile --windowed \
        --name Entryptor \
        --add-data "src:src" \
        --hidden-import PyQt6.QtCore \
        --hidden-import PyQt6.QtGui \
        --hidden-import PyQt6.QtWidgets \
        --hidden-import cryptography \
        src/main.py
    displayName: 'Build Linux Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'entryptor-linux'
    displayName: 'Publish Build Artifacts'
