# Entryptor CI/CD Pipeline
# Build, test, and package Python application for multiple platforms

trigger:
- main

pr:
- main

variables:
  pythonVersion: '3.11'

stages:
- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestPython311
    displayName: 'Test Python 3.11 (Primary)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: pipelines/templates/test-steps.yml
      parameters:
        pythonVersion: '3.11'
        platform: 'Linux'

- stage: Build
  displayName: 'Build Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: BuildLinux
    displayName: 'Build Linux Application'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: pipelines/templates/build-steps.yml
      parameters:
        pythonVersion: $(pythonVersion)
        platform: 'Linux'
        artifactName: 'entryptor-linux'

- stage: Package
  displayName: 'Package Stage'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: CreateRelease
    displayName: 'Create Release Package'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: pipelines/templates/package-steps.yml
      parameters:
        pythonVersion: $(pythonVersion)
