# Entryptor Minimal CI Pipeline - GitHub Actions
# Ultra-fast pipeline for immediate feedback

name: Minimal CI

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements*.txt'

env:
  PYTHON_VERSION: '3.11'

jobs:
  minimal-check:
    name: Minimal Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy pytest
        pip install -r requirements.txt --no-deps
    
    - name: Quick style check
      run: |
        echo "🎨 Style check..."
        ruff check src/ --quiet
    
    - name: Quick type check
      run: |
        echo "🔍 Type check..."
        mypy src/ --ignore-missing-imports --no-error-summary
    
    - name: Smoke test
      run: |
        echo "💨 Smoke test..."
        python -c "
        import sys
        sys.path.append('src')
        try:
            from crypto.encryption import AESEncryption
            from utils.file_utils import FileValidator
            print('✅ Core imports working')
        except Exception as e:
            print(f'❌ Import error: {e}')
            sys.exit(1)
        "
